export const STATE_LIST_SUCCESS = "STATE_LIST_SUCCESS";
export const STATE_LIST_ERROR = "STATE_LIST_ERROR";

export const DISTRICT_LIST_SUCCESS = "DISTRICT_LIST_SUCCESS";
export const DISTRICT_LIST_ERROR = "DISTRICT_LIST_ERROR";

export const SLOT_LIST_INFO_SUCCESS = "SLOT_LIST_INFO_SUCCESS";
export const SLOT_LIST_INFO_ERROR = "SLOT_LIST_INFO_ERROR";
